# Generated by Django 4.2.7 on 2023-12-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asad', '0002_alter_kategori_options_alter_kontak_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
